### ISSUE TITLE
GitHubSource pods fails to run: chdir to /home/nonroot permission denied

### ISSUE THREAD

**Issue by makandre** [knative-sandbox/eventing-github#139]
**Describe the bug**

I want to install and run GitHubSource on my cluster (it's OCP 4.6).  Both the controller manager and webhook pods fail to run with following error:

```
Error: container create failed: time="2021-03-10T17:05:04Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
```

I worked around that by adding the respective service accounts to the `anyuid` scc, but the GitHubSource pod itself in my application namespace has same problem and it's running under the `default` service account.

 **Expected behavior**

GitHubSource pods can run without special privileges

 **To Reproduce**

Install GitHubSource to OCP cluster

 **Knative release version**

`0.19.0`

 **Additional context**

I have played with older releases of GitHubSource in the past and this was not an issue.

**Comment by lionelvillard** [comment]
@makandre Can you try adding this to the operator and webhook cluster roles:

```
 apiGroups:
     - security.openshift.io
     resources:
     - securitycontextconstraints
     resourceNames:
     - anyuid
     verbs:
     - use
```
